### ISSUE TITLE
WhatsClient bug

### ISSUE THREAD

**Issue by SubZer0GLX** [gfaraj/super-bot#10]
i can't start the client for whatsapp because this give for me this following output:

Starting SuperBot for Whatsapp...
Loading WAPI...
Checking Whatsapp Web API...
(node:11348) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: window.WAPI.isReady is not a function
    at __puppeteer_evaluation_script__:2:33
    at ExecutionContext._evaluateInternal (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at async WhatsappClient.start (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\clients\whatsapp\src\WhatsappClient.js:109:16)
    at async main (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\clients\whatsapp\src\app.js:8:5)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\node_modules\puppeteer\lib\Page.js:833:43)
    at Page.<anonymous> (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\node_modules\puppeteer\lib\helper.js:112:23)
    at WhatsappClient.start (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\clients\whatsapp\src\WhatsappClient.js:109:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\clients\whatsapp\src\app.js:8:5)
(node:11348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

is it possible to correct? i was making AI modules,

**Comment by gfaraj** [comment]
You're right, this is happening in a clean install for some reason. I will look into it. Thanks for reporting it.

**Comment by gfaraj** [comment]
Fixed it now, get latest from the master branch. Let me know if you have any issues.
